export const BUILT_IN_TEMPLATES = [
  {
    id: "tpl_blank",
    name: "Blank Tree",
    description: "Start from scratch with just a Trigger node.",
    icon: "Zap",
    accent: "violet",
    campaign_type: "custom",
    nodes: [
      {
        node_id: "n_start",
        type: "start",
        position_x: 200,
        position_y: 200,
        data: { title: "When session starts", variables: [] },
      },
    ],
    edges: [],
  },
  {
    id: "tpl_mva",
    name: "MVA Qualification",
    description:
      "Standard motor vehicle accident qualifier with state, fault, injuries, treatment, attorney, recency.",
    icon: "Phone",
    accent: "sky",
    campaign_type: "mva",
    nodes: [
      {
        node_id: "n_start",
        type: "start",
        position_x: 40,
        position_y: 320,
        data: {
          title: "Session start",
          variables: [
            { name: "utm_source", default: "" },
            { name: "lp_id", default: "" },
          ],
        },
      },
      {
        node_id: "n_state",
        type: "single_choice",
        position_x: 360,
        position_y: 280,
        data: {
          title: "State eligibility",
          question: "What state did the accident happen in?",
          variable: "state",
          options: ["California", "Texas", "Florida", "New York", "Other"],
        },
      },
      {
        node_id: "n_hard_state",
        type: "result",
        position_x: 720,
        position_y: 560,
        data: {
          title: "Out of footprint",
          kind: "disqualified",
          reason: "State not covered",
        },
      },
      {
        node_id: "n_fault",
        type: "single_choice",
        position_x: 720,
        position_y: 200,
        data: {
          title: "Fault",
          question: "Were you at fault for the accident?",
          variable: "at_fault",
          options: ["No, other driver", "Partially", "Yes, I was at fault"],
        },
      },
      {
        node_id: "n_hard_fault",
        type: "result",
        position_x: 1080,
        position_y: 380,
        data: {
          title: "At-fault DQ",
          kind: "disqualified",
          reason: "Claimant at fault",
        },
      },
      {
        node_id: "n_injuries",
        type: "multi_choice",
        position_x: 1080,
        position_y: 80,
        data: {
          title: "Injuries sustained",
          question: "Select any injuries you sustained.",
          variable: "injuries",
          options: [
            "Whiplash",
            "Broken bone",
            "TBI / concussion",
            "Back / spine",
            "Soft tissue",
            "None",
          ],
          rules: [
            { name: "Serious", expr: "includes Broken bone OR TBI OR Back" },
            { name: "Minor only", expr: "only soft tissue / whiplash" },
          ],
        },
      },
      {
        node_id: "n_soft",
        type: "result",
        position_x: 1440,
        position_y: 280,
        data: {
          title: "Nurture - Minor",
          kind: "nurture",
          reason: "Soft-tissue only",
          campaign: "MVA nurture 30d",
        },
      },
      {
        node_id: "n_treated",
        type: "single_choice",
        position_x: 1440,
        position_y: -80,
        data: {
          title: "Medical treatment",
          question: "Did you receive medical treatment within 14 days?",
          variable: "treated",
          options: ["Yes, immediately", "Yes, within 14 days", "No"],
        },
      },
      {
        node_id: "n_attorney",
        type: "single_choice",
        position_x: 1800,
        position_y: -80,
        data: {
          title: "Existing attorney",
          question: "Are you currently represented by an attorney?",
          variable: "has_attorney",
          options: ["No", "Yes"],
        },
      },
      {
        node_id: "n_hard_attorney",
        type: "result",
        position_x: 2160,
        position_y: 140,
        data: {
          title: "Represented",
          kind: "disqualified",
          reason: "Already retained counsel",
        },
      },
      {
        node_id: "n_phone",
        type: "phone_input",
        position_x: 2160,
        position_y: -160,
        data: {
          title: "Best phone",
          prompt: "What's the best number to reach you?",
          variable: "phone",
          hlr: true,
        },
      },
      {
        node_id: "n_submit",
        type: "submit",
        position_x: 2520,
        position_y: -160,
        data: { title: "Submit to buyer", destination: "Lead", trustedform: true },
      },
      {
        node_id: "n_qualified",
        type: "result",
        position_x: 2880,
        position_y: -160,
        data: {
          title: "Qualified",
          kind: "qualified",
          buyer: "MVA Premium A",
          payout: 145,
        },
      },
    ],
    edges: [
      { source: "n_start", sourceHandle: "next", target: "n_state" },
      { source: "n_state", sourceHandle: "opt_0", target: "n_fault" },
      { source: "n_state", sourceHandle: "opt_1", target: "n_fault" },
      { source: "n_state", sourceHandle: "opt_2", target: "n_fault" },
      { source: "n_state", sourceHandle: "opt_3", target: "n_fault" },
      { source: "n_state", sourceHandle: "opt_4", target: "n_hard_state" },
      { source: "n_fault", sourceHandle: "opt_0", target: "n_injuries" },
      { source: "n_fault", sourceHandle: "opt_1", target: "n_injuries" },
      { source: "n_fault", sourceHandle: "opt_2", target: "n_hard_fault" },
      { source: "n_injuries", sourceHandle: "rule_0", target: "n_treated" },
      { source: "n_injuries", sourceHandle: "rule_1", target: "n_soft" },
      { source: "n_injuries", sourceHandle: "any", target: "n_soft" },
      { source: "n_treated", sourceHandle: "opt_0", target: "n_attorney" },
      { source: "n_treated", sourceHandle: "opt_1", target: "n_attorney" },
      { source: "n_treated", sourceHandle: "opt_2", target: "n_soft" },
      { source: "n_attorney", sourceHandle: "opt_0", target: "n_phone" },
      { source: "n_attorney", sourceHandle: "opt_1", target: "n_hard_attorney" },
      { source: "n_phone", sourceHandle: "next", target: "n_submit" },
      { source: "n_submit", sourceHandle: "ok", target: "n_qualified" },
      { source: "n_submit", sourceHandle: "err", target: "n_soft" },
    ],
  },
  {
    id: "tpl_mass_tort",
    name: "Mass Tort Eligibility",
    description:
      "Generic mass tort screener: usage, dates, injuries, then qualified.",
    icon: "AlertTriangle",
    accent: "amber",
    campaign_type: "mass_tort",
    nodes: [
      {
        node_id: "n_start",
        type: "start",
        position_x: 40,
        position_y: 240,
        data: { title: "Mass tort intake", variables: [] },
      },
      {
        node_id: "n_used",
        type: "single_choice",
        position_x: 360,
        position_y: 240,
        data: {
          title: "Product used",
          question: "Did you use the product in question?",
          variable: "used",
          options: ["Yes", "No", "Not sure"],
        },
      },
      {
        node_id: "n_dq_notused",
        type: "result",
        position_x: 720,
        position_y: 400,
        data: {
          title: "Did not use product",
          kind: "disqualified",
          reason: "Required exposure not met",
        },
      },
      {
        node_id: "n_dates",
        type: "single_choice",
        position_x: 720,
        position_y: 100,
        data: {
          title: "Usage dates",
          question: "When did you use the product?",
          variable: "dates",
          options: ["Before 2010", "2010-2020", "After 2020"],
        },
      },
      {
        node_id: "n_injury",
        type: "single_choice",
        position_x: 1080,
        position_y: 100,
        data: {
          title: "Injury or diagnosis",
          question: "Did you experience a related injury or diagnosis?",
          variable: "injury",
          options: ["Yes, diagnosed", "Symptoms only", "No"],
        },
      },
      {
        node_id: "n_dq_noinjury",
        type: "result",
        position_x: 1440,
        position_y: 280,
        data: {
          title: "No qualifying injury",
          kind: "disqualified",
          reason: "No diagnosis or symptoms",
        },
      },
      {
        node_id: "n_phone",
        type: "phone_input",
        position_x: 1440,
        position_y: -60,
        data: {
          title: "Phone",
          prompt: "Best number to reach you?",
          variable: "phone",
          hlr: true,
        },
      },
      {
        node_id: "n_submit",
        type: "submit",
        position_x: 1800,
        position_y: -60,
        data: { title: "Submit to firm", destination: "Lead", trustedform: true },
      },
      {
        node_id: "n_qualified",
        type: "result",
        position_x: 2160,
        position_y: -60,
        data: {
          title: "Qualified",
          kind: "qualified",
          buyer: "Mass Tort Partner",
          payout: 250,
        },
      },
    ],
    edges: [
      { source: "n_start", sourceHandle: "next", target: "n_used" },
      { source: "n_used", sourceHandle: "opt_0", target: "n_dates" },
      { source: "n_used", sourceHandle: "opt_1", target: "n_dq_notused" },
      { source: "n_used", sourceHandle: "opt_2", target: "n_dq_notused" },
      { source: "n_dates", sourceHandle: "opt_0", target: "n_injury" },
      { source: "n_dates", sourceHandle: "opt_1", target: "n_injury" },
      { source: "n_dates", sourceHandle: "opt_2", target: "n_injury" },
      { source: "n_injury", sourceHandle: "opt_0", target: "n_phone" },
      { source: "n_injury", sourceHandle: "opt_1", target: "n_phone" },
      { source: "n_injury", sourceHandle: "opt_2", target: "n_dq_noinjury" },
      { source: "n_phone", sourceHandle: "next", target: "n_submit" },
      { source: "n_submit", sourceHandle: "ok", target: "n_qualified" },
    ],
  },
  {
    id: "tpl_slipfall",
    name: "Slip & Fall",
    description: "Premises liability screener: location, injury, treatment, fault.",
    icon: "AlertTriangle",
    accent: "fuchsia",
    campaign_type: "slip_and_fall",
    nodes: [
      {
        node_id: "n_start",
        type: "start",
        position_x: 40,
        position_y: 200,
        data: { title: "Slip & fall intake", variables: [] },
      },
      {
        node_id: "n_location",
        type: "single_choice",
        position_x: 360,
        position_y: 200,
        data: {
          title: "Location type",
          question: "Where did the incident happen?",
          variable: "location",
          options: [
            "Business / store",
            "Apartment / rental",
            "Public property",
            "Private home",
            "Other",
          ],
        },
      },
      {
        node_id: "n_dq_priv",
        type: "result",
        position_x: 720,
        position_y: 400,
        data: {
          title: "Private home DQ",
          kind: "disqualified",
          reason: "Private residence",
        },
      },
      {
        node_id: "n_injury",
        type: "single_choice",
        position_x: 720,
        position_y: 50,
        data: {
          title: "Injury severity",
          question: "Did you require medical treatment?",
          variable: "treated",
          options: ["Hospitalized", "ER / urgent care", "Doctor visit", "No treatment"],
        },
      },
      {
        node_id: "n_dq_notreat",
        type: "result",
        position_x: 1080,
        position_y: 280,
        data: {
          title: "No treatment DQ",
          kind: "disqualified",
          reason: "No medical treatment",
        },
      },
      {
        node_id: "n_phone",
        type: "phone_input",
        position_x: 1080,
        position_y: -60,
        data: {
          title: "Phone",
          prompt: "Best contact number?",
          variable: "phone",
          hlr: true,
        },
      },
      {
        node_id: "n_qualified",
        type: "result",
        position_x: 1440,
        position_y: -60,
        data: {
          title: "Qualified",
          kind: "qualified",
          buyer: "Slip & Fall Partner",
          payout: 90,
        },
      },
    ],
    edges: [
      { source: "n_start", sourceHandle: "next", target: "n_location" },
      { source: "n_location", sourceHandle: "opt_0", target: "n_injury" },
      { source: "n_location", sourceHandle: "opt_1", target: "n_injury" },
      { source: "n_location", sourceHandle: "opt_2", target: "n_injury" },
      { source: "n_location", sourceHandle: "opt_3", target: "n_dq_priv" },
      { source: "n_location", sourceHandle: "opt_4", target: "n_injury" },
      { source: "n_injury", sourceHandle: "opt_0", target: "n_phone" },
      { source: "n_injury", sourceHandle: "opt_1", target: "n_phone" },
      { source: "n_injury", sourceHandle: "opt_2", target: "n_phone" },
      { source: "n_injury", sourceHandle: "opt_3", target: "n_dq_notreat" },
      { source: "n_phone", sourceHandle: "next", target: "n_qualified" },
    ],
  },
  {
    id: "tpl_workers_comp",
    name: "Workers Comp",
    description: "Work injury screener: employer type, injury, reporting, attorney.",
    icon: "FileCheck2",
    accent: "emerald",
    campaign_type: "workers_comp",
    nodes: [
      {
        node_id: "n_start",
        type: "start",
        position_x: 40,
        position_y: 200,
        data: { title: "Workers comp intake", variables: [] },
      },
      {
        node_id: "n_reported",
        type: "single_choice",
        position_x: 360,
        position_y: 200,
        data: {
          title: "Reported to employer",
          question: "Did you report the injury to your employer within 30 days?",
          variable: "reported",
          options: ["Yes", "No, more than 30 days", "Not sure"],
        },
      },
      {
        node_id: "n_dq_unreported",
        type: "result",
        position_x: 720,
        position_y: 360,
        data: {
          title: "Past reporting window",
          kind: "disqualified",
          reason: "Reporting deadline missed",
        },
      },
      {
        node_id: "n_treatment",
        type: "single_choice",
        position_x: 720,
        position_y: 50,
        data: {
          title: "Medical treatment",
          question: "Have you received medical treatment?",
          variable: "treated",
          options: ["Yes, ongoing", "Yes, completed", "No"],
        },
      },
      {
        node_id: "n_phone",
        type: "phone_input",
        position_x: 1080,
        position_y: 50,
        data: {
          title: "Phone",
          prompt: "Best contact number?",
          variable: "phone",
          hlr: true,
        },
      },
      {
        node_id: "n_qualified",
        type: "result",
        position_x: 1440,
        position_y: 50,
        data: {
          title: "Qualified",
          kind: "qualified",
          buyer: "Workers Comp Partner",
          payout: 75,
        },
      },
    ],
    edges: [
      { source: "n_start", sourceHandle: "next", target: "n_reported" },
      { source: "n_reported", sourceHandle: "opt_0", target: "n_treatment" },
      { source: "n_reported", sourceHandle: "opt_1", target: "n_dq_unreported" },
      { source: "n_reported", sourceHandle: "opt_2", target: "n_treatment" },
      { source: "n_treatment", sourceHandle: "opt_0", target: "n_phone" },
      { source: "n_treatment", sourceHandle: "opt_1", target: "n_phone" },
      { source: "n_treatment", sourceHandle: "opt_2", target: "n_phone" },
      { source: "n_phone", sourceHandle: "next", target: "n_qualified" },
    ],
  },
];