export const NODE_TYPE_META = {
  start_page:              { icon: "🚀", label: "Start Page",           desc: "Entry point with URL param capture" },
  custom_page:             { icon: "📄", label: "Custom Page",          desc: "Rich HTML content page" },
  multiple_choice:         { icon: "☑️",  label: "Multiple Choice",      desc: "Select multiple options" },
  single_select:           { icon: "🔘", label: "Single Select",        desc: "Pick one option" },
  checkbox_multi_select:   { icon: "✅", label: "Checkbox Multi-Select", desc: "Checkbox-style multi-select" },
  dropdown:                { icon: "🔽", label: "Dropdown",             desc: "Dropdown select (great for states)" },
  text_field:              { icon: "📝", label: "Text Field",           desc: "Short or long text input" },
  text_block:              { icon: "📋", label: "Text Block",           desc: "Display-only text or HTML" },
  information:             { icon: "ℹ️",  label: "Information",          desc: "Info card with optional image" },
  slider:                  { icon: "🎚️", label: "Slider",               desc: "Range or number slider" },
  address:                 { icon: "🏠", label: "Address",              desc: "Address fields" },
  date_picker:             { icon: "📅", label: "Date Picker",          desc: "Date selection with bucketing" },
  datetime_picker:         { icon: "🕐", label: "Date & Time",          desc: "Combined date/time picker" },
  decision_node:           { icon: "🔀", label: "Decision Node",        desc: "Rule-based branching" },
  form:                    { icon: "📮", label: "Contact Form",         desc: "Lead capture form" },
  transition:              { icon: "➡️",  label: "Transition",           desc: "Animated transition step" },
  notification_sms:        { icon: "💬", label: "SMS Notification",     desc: "Send an SMS" },
  notification_email:      { icon: "📧", label: "Email Notification",   desc: "Send an email" },
  notification_whatsapp:   { icon: "💚", label: "WhatsApp",             desc: "WhatsApp message" },
  notification_messenger:  { icon: "💙", label: "Messenger",            desc: "Facebook Messenger" },
  notification_telegram:   { icon: "✈️",  label: "Telegram",             desc: "Telegram message" },
  phone_verification:      { icon: "📱", label: "Phone Verification",   desc: "OTP phone verify" },
  webhook_api:             { icon: "🔗", label: "Webhook / API",        desc: "Call external API" },
  results_page:            { icon: "🎯", label: "Results Page",         desc: "Outcome display" },
};